In [1]:
a = [1, 2, 3, 4]

In [2]:
a

[1, 2, 3, 4]

In [3]:
a[2]

3

In [4]:
dd = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
dd

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
dd[0][2]

3

**RANK** - A tensor's rank tells us **how many indexs** are needed to refer to a specific element within the tensor,
whereas, **Axes** - An axes of a tensor is a **specific dimension** of a tensor. 

**Lenght of axes** - The length of each axes tells us **how many indexes are available along each axis**.

**Shape** - The shape of a tensor gives us the **length of each axis of the tensor.**

In [7]:
dd[0][0]

1

In [8]:
dd[0][1]

2

In [9]:
dd[0][2]

3

In [1]:
import torch
print(torch.__version__)

1.4.0


In [3]:
dd = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
type(t)

torch.Tensor

In [5]:
t.shape

torch.Size([3, 3])

**We can say - The torch.tensor(dd) has rank - 2 with shape of 3x3.**


In [12]:
t = torch.tensor([[[2, 3, 4, 4],[2, 3, 4, 5]]])

In [13]:
t.shape

torch.Size([1, 2, 4])

In [14]:
dd = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
dd[1]

[4, 5, 6]

1. With tensors, the elements of the last axis are always ______. (1) arrays, (2) tuples, **(3) numbers**, (4) tensors

2. If we say that a tensor is a rank-2 tensor, we mean that the tensor has 2 dimension or equivalently, the tensor has two ________. (1) rows (2) elements (3) columns **(4) axes.** 

3. The rank of a tensor tells us how many _______ are required to access(refer to) a specific ______ contained within the tensor data structure. **(1) indices, element** (2) indices, axis (3) elements, axis (4) rows, elements.

4. The rank of a tensor refers to the number of ______ present within the tensor. (1) rows, (2) columns, **(3) dimensions** (4) elements.


## Remember in case of CNN-

The shape of the CNN input is typically len([A0,A1,A2,A3]) = 4, i.e. we have a rank-4 tensor with 4 axes. Each index in a tensor shape represents a specific axes and the value at each index gives us the lenght of this corresponding axis. 

A3 - number , where A0-A2 - multidimensional array.

For images the raw data comes in the form of pixels that are represented by a number. 
[Batch size,Color Channel,Height(vertical),Width(horizontal)]

After Convolution,
[?,feature maps, H,W]



**PyTorch - data structure.** 

### PyTorch Tensors Explained - NN Programming

- Tensor Class 
    Tensors in PyTorch are represnted using torch.tensor class.
- Tensor attributes 
    t.dtype - type of data
    t.device - 
    t.layout - how tensor data is laid out 
- Creation options using data


In [16]:
import torch
import numpy as np

In [19]:
t = torch.Tensor()
type(t)

torch.Tensor

In [20]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [21]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [22]:
data = np.array([1, 2, 3])
type(data)

numpy.ndarray

In [29]:
#Example

t1 = torch.tensor([1, 2, 2])
t2 = torch.tensor([1.,2.,3.])

print(t1.dtype)
print(t2.dtype)

print(t1+t2)

torch.int64
torch.float32
tensor([2., 4., 5.])


In [30]:
t1 = torch.tensor([1, 2, 3])
t2 = t1.cude()

print(t1.device)
print(t2.device)
print(t1+t2)

AttributeError: 'Tensor' object has no attribute 'cude'

### Creating tensors from data 

Primary ways are --
1. torch.Tensor(data)
2. torch.tensor(data)
3. torch.as_tensor(data)
4. torch.from_numpy(data)

In [31]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [32]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [33]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [34]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [35]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

**Creation options without data**

In [36]:
torch.eye(2)   # identity matrix

tensor([[1., 0.],
        [0., 1.]])

In [37]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [38]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [39]:
torch.rand(2,2)

tensor([[0.3257, 0.7313],
        [0.7454, 0.0655]])

### CReating PyTorch Tensors For DL - Best Options 