In [1]:
import torch 
import torch.nn as nn

print(torch.__version__)

1.4.0


## 10. Flatten, Reshape and Squeeze Explained 

#### Tensor operation 

1. Reshaping operations
2. Element-wise operation
3. Reduction operations
4. Access operations



In [10]:
# Consider the following tensor

t = torch.tensor([
    [1, 1,1,1],
    [2,2,2,2],
    [3,3,3,3],
], dtype = torch.float32)
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [11]:
t.size()

torch.Size([3, 4])

In [12]:
t.shape

torch.Size([3, 4])

In [13]:
len(t.shape)  # tells about the rank 

2

**We can also deduce/analysis, the number of elements within the tensor.**

The number of elements in tensor = the product of the shape's component values.

In [14]:
torch.tensor(t.shape).prod()

tensor(12)

In [15]:
# In Pytorch, there is a dedicated function for this:
t.numel()

12

**Reshaping a tensor in PyTorch**

In [18]:
print(t.reshape([12,1]))
print(t.reshape([4,3]))
print(t.reshape([6,2]))
print(t.reshape([2,2,3]))

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])
tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])
tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])
tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])


**Changing shape by Squeezing and Unsqueezing**

The next way we can change the shape of our tensors is by squeezing and unsqueezing them.

- Squeezing a tensor removes the dimensions or axes that have a length of one.
- Unsqueezing a tensor adds a dimension with a length of one.

In [19]:
print(t.reshape([1, 12]))
print(t.reshape([1, 12]).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [20]:
print(t.reshape([1, 12]).squeeze())
print(t.reshape([1, 12]).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [21]:
print(t.reshape([1, 12]).squeeze().unsqueeze(dim = 0))
print(t.reshape([1, 12]).squeeze().unsqueeze(dim = 0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


**Flatten a Tensor**

- To removes all dimensions except for one

In [22]:
def flatten(t):
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t

In [23]:
t = torch.ones(4,3)
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [24]:
flatten(t)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Concatenating Tensors**

-cat() function

In [25]:
t1 = torch.tensor([[1,2],[3,4]])
t2 = torch.tensor([[5,6],[7,8]])

In [26]:
torch.cat((t1, t2), dim = 0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [27]:
torch.cat((t1, t2), dim = 1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [28]:
torch.cat((t1, t2))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [29]:
torch.cat((t1, t2), dim = 0).shape

torch.Size([4, 2])

In [30]:
torch.cat((t1, t2), dim = 1).shape

torch.Size([2, 4])

In [32]:
def flatten(t):
    t = t.reshape(1, t.size()[0] * t.size()[1])
    t = t.squeeze()
    return t

2

In [ ]:
def flatten(t):
    t = t.reshape(1, t.numel())
    t = t.squeeze()
    return t